version: "3.6"
services:
  mongo:
    image: mongo:4.4.4
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exist 0"

  autoclub__156:
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    healthcheck:
      test: "exist 0"
